// user_role// ROLE TABLE
CREATE TABLE ROLE(
     MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT,
     MEMBER_NAME VARCHAR(20),
     PRIMARY KEY (MEMBER_ID)
);

// USER x ROLE MAPPING TABLE - USER_ROLE MANY-TO-MANY
CREATE TABLE USER_ROLE(
    MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (member_id, role_id),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(MEMBER_ID)
);